Routers = {
    "TE100-S5": {
        "Model": "TE100-S5",
        "Product Title": "5-Port 10/100 Mbps Fast Ethernet Switch",
        "10/100 Mbps": "5x",
        "Forwarding Capacity": "1Gbps",
        "Data RAM Buffering": "384 Kbytes",
        "202.3x Flow Control": "+",
        "MAC address entries": "2k",
        "enclosure Material": "Plastic",
        "GR66Nnet": "-",
        "Warranty": "3-year limited",
    },
    "TE100-S8": {
        "Model": "TE100-S8",
        "Product Title": "8-port 10/100 Mbps Ethernet Switch",
        "10/100 Mbps": "8x",
        "Forwarding Capacity": "1.6 Gbps",
        "Data RAM Buffering": "512 Kbytes",
        "202.3x Flow Control": "+",
        "MAC address entries": "2k",
        "enclosure Material": "Plastic",
        "GR66Nnet": "-",
        "Warranty": "3-year limited",
    },
    "TE100-S50g": {
        "Model": "TE100-S50g",
        "Product Title": "5-Port 10/100 Mbps GREENnet Switch",
        "10/100 Mbps": "5x",
        "Forwarding Capacity": "1Gbps",
        "Data RAM Buffering": "384 Kbytes",
        "202.3x Flow Control": "+",
        "MAC address entries": "1k",
        "enclosure Material": "Metal Desktop",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S80g": {
        "Model": "TE100-S80g",
        "Product Title": "9-port 10/100 Mbps GREENnet Switch",
        "10/100 Mbps": "5x",
        "Forwarding Capacity": "1.6 Gbps",
        "Data RAM Buffering": "768 Kbytes",
        "202.3x Flow Control": "+",
        "MAC address entries": "1k",
        "enclosure Material": "Metal Desktop",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S16g": {
        "Model": "TE100-S16g",
        "Product Title": "16-port 10/100 Mbps GREENnet Switch",
        "10/100 Mbps": "16x",
        "Forwarding Capacity": "3.2 Gbps",
        "Data RAM Buffering": "1.25 Mbits",
        "202.3x Flow Control": "+",
        "MAC address entries": "8K",
        "enclosure Material": "Metal Rackmount",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S24g": {
        "Model": "TE100-S24g",
        "Product Title": "24-port 10/100 Mbps GREENnet Switch",
        "10/100 Mbps": "24x",
        "Forwarding Capacity": "4.8 Gbps",
        "Data RAM Buffering": "1.25 Mbits",
        "202.3x Flow Control": "+",
        "MAC address entries": "8k",
        "enclosure Material": "Metal Rackmount",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
}
model = input('Введите название роутера: ')
print(f'{Routers[model]}')
